LocalUsers/urls.py
from django.conf.urls import url
from LocalUsers import views

app_name = 'Authent'

urlpatterns = [
    url(r'^login$',
        views.user_login,
        name="login"
        ),
    url(r'^logout$',
        views.user_logout,
        name="logout"
        ),
    url(r'^login/changepwd$',
        views.password_change_mandatory,
        name="loginchangepwd"
        ),
    url(r'^login/lost-password$',
        views.password_lost,
        name='password_lost'
        ),
    url(r'^user/myprofile$',
        views.myprofile,
        name="myprofile"
        ),
    url(r'^user/(?P<userid>\d+)/edit$',
        views.edit_user,
        name="edit_user"
        ),
    url(r'^user/(?P<userid>\d+)/blockunblock$',
        views.block_unblock_user,
        name="block_unblock_user"
        ),
    url(r'^user/new$',
        views.new_user,
        name="new_user"
        ),
    url(r'^users/list/?(/(?P<emailcontains>[^/]{0,})/)?$',
        views.list_users,
        name="list_users"
        ),
    url(r'^entity/new$',
        views.new_entity,
        name="new_entity"
        ),
    url(r'^entity/list$',
        views.list_entities,
        name="list_entities"
        ),
    url(r'^entity/(?P<entityid>\d+)/edit/?$',
        views.edit_entity,
        name="edit_entity"
        ),
    url(r'^entity/(?P<entityid>\d+)/listadmins/?$',
        views.list_entity_admins,
        name="list_entity_admins"
        ),
    url(r'^entity/(?P<entityid>\d+)/addadmin/?$',
        views.add_entity_admin,
        name="add_entity_admin"
        ),
    url(r'^entity/(?P<entityid>\d+)/removeadmin/(?P<adminid>\d+)/?$',
        views.remove_entity_admin,
        name="remove_entity_admin"
        ),
    url(r'^region/new$',
        views.new_region,
        name="new_region"
        ),
    url(r'^region/list$',
        views.list_regions,
        name="list_regions"
        ),
    url(r'^region/(?P<regionid>\d+)/edit/?$',
        views.edit_region, name="edit_region"
        ),
    url(r'^region/(?P<regionid>\d+)/listusers/?$',
        views.list_region_users, name="list_region_users"
        ),
    url(r'^region/(?P<regionid>\d+)/adduser/?$',
        views.add_region_user, name="add_region_user"
        ),
    url(r'^region/(?P<regionid>\d+)/removeuser/(?P<userid>\d+)/?$',
        views.remove_region_user,
        name="remove_region_user"
        ),
]

Main/urls.py
from django.conf.urls import url
from Main import views

app_name = 'Main'

urlpatterns = [
    url(r'^$',
        views.index,
        name="index"),
    url(r'^$',
        views.campaign_overview,
        name="campaign_overview"),
    url(r'^targets$',
        views.campaign_targets,
        name="campaign_targets"),
    url(r'^campaigns/targets/createlist$',
        views.campaign_create_targets_list,
        name="campaign_create_targets_list"),
    url(r'^targets/deletelist/(?P<listid>\d+)$',
        views.campaign_delete_targets_list,
        name="campaign_delete_targets_list"),
    url(r'^targets/editlist/(?P<listid>\d+)$',
        views.campaign_edit_targets_list,
        name="campaign_edit_targets_list"),
    url(r'^targets/importtargerts/(?P<listid>\d+)$',
        views.campaign_import_targets_list,
        name="campaign_import_targets_list"),
    url(r'^targets/exporttargerts/(?P<listid>\d+)$',
        views.campaign_export_targets_list,
        name="campaign_export_targets_list"),
    url(r'^targets/createtarget/(?P<listid>\d+)$',
        views.campaign_create_target,
        name="campaign_create_target"),
    url(r'^targets/removetarget/(?P<listid>\d+)/(?P<targetid>\d+)$',
        views.campaign_delete_target,
        name="campaign_delete_target"),
    url(r'^targets/edittarget/(?P<listid>\d+)/(?P<targetid>\d+)$',
        views.campaign_edit_target,
        name="campaign_edit_target"),
    url(r'^targets/listtargets/(?P<listid>\d+)/(?P<page>\d+)?$',
        views.campaign_list_targets,
        name="campaign_list_targets"),
    url(r'^targets/lists/(?P<page>\d+)?$',
        views.campaign_list_targets_list,
        name="campaign_list_targets_list"),
    url(r'^templates$',
        views.campaign_templates,
        name="campaign_templates"),
    url(r'^templates/create/(?P<typeid>\d)(?:/(?P<duplicateid>\d+))?$',
        views.campaign_create_template,
        name="campaign_create_template"),
    url(r'^templates/edit/(?P<typeid>\d)/(?P<templateid>\d+)$',
        views.campaign_edit_template,
        name="campaign_edit_template"),
    url(r'^templates/delete/(?P<templateid>\d+)$',
        views.campaign_delete_template,
        name="campaign_delete_template"),
    url(r'^templates/view/(?P<templateid>\d+)$',
        views.campaign_view_template,
        name="campaign_view_template"),
    url(r'^templates/list/(?P<page>\d+)?$',
        views.campaign_list_template,
        name="campaign_list_template"),
    url(r'^campaigns$',
        views.campaign_campaigns,
        name="campaign_campaigns"),
    url(r'^campaigns/running$',
        views.campaign_running_campaigns,
        name="campaign_running_campaigns"),
    url(r'^campaigns/create/(?P<typeid>\d)(?:/(?P<duplicateid>\d+))?$',
        views.campaign_create_campaign,
        name="campaign_create_campaign"),
    url(r'^campaigns/edit/(?P<typeid>\d)/(?P<campaignid>\d+)$',
        views.campaign_edit_campaign,
        name="campaign_edit_campaign"),
    url(r'^campaigns/delete/(?P<campaignid>\d+)$',
        views.campaign_delete_campaign,
        name="campaign_delete_campaign"),
    url(r'^campaigns/test/(?P<campaignid>\d+)$',
        views.campaign_test_campaign,
        name="campaign_test_campaign"),
    url(r'^campaigns/download/(?P<campaignid>\d+)$',
        views.campaign_download_results,
        name="campaign_download_results"),
    url(r'^campaigns/dasbhoard/(?P<campaignid>\d+)$',
        views.campaign_display_dashboard,
        name="campaign_display_dashboard"),
    url(r'^campaigns/reportids/(?P<campaignid>\d+)$',
        views.campaign_submit_reported_ids,
        name="campaign_submit_reported_ids"),
    url(r'^campaigns/list/(?P<page>\d+)?$',
        views.campaign_list_campaigns,
        name="campaign_list_campaigns"),
    url(r'^campaigns/list-running/(?P<page>\d+)?$',
        views.campaign_list_running_campaigns,
        name="campaign_list_running_campaigns"),

    url(r'^admin/entities$',
        views.admin_entities,
        name="admin_entities"),
    url(r'^admin/regions$',
        views.admin_regions,
        name="admin_regions"),
    url(r'^admin/users$',
        views.admin_users,
        name="admin_users"),
    url(r'^result/click/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_target_click,
        name="campaign_target_click"),
    url(r'^result/displayawareness/(?P<campaignid>\d+)/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_display_awareness,
        name="campaign_display_awareness"),
    url(r'^result/getimage/(?P<templateid>\d+)/(?P<imgid>img\d+)$',
        views.internet_explorer_img_hack,
        name="getimage"),
    url(r'^result/img/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_target_openmail,
        name="campaign_target_openmail"),
    url(r'^result/report/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_target_reportmail,
        name="campaign_target_reportmail"),
    url(r'^result/attach/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_target_openattachment,
        name="campaign_target_openattachment"),
    url(r'^2985836c7501af76a0bdd92f1d120cd2/domains_feed',
        views.domains_feed,
        name="domains_feed"),
]

Swordphish/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('LocalUsers.urls')),
    url(r'^', include('Main.urls')),
]

LocalUsers/views.py
# coding: utf8

from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseForbidden
from django.core.mail import EmailMessage
from django.conf import settings
from django.contrib.auth.models import User

from LocalUsers.forms import LostpasswordForm, SwordphishUserForm, CreateUserForm, UserForm
from LocalUsers.forms import AddAdminForm, RegionForm, AddUserInRegionForm, ChangePasswordForm
from LocalUsers.forms import EntityForm, EditMyProfileForm
from LocalUsers.models import SwordphishUser, Entity, Region, RegionMembership

# Create your views here.


def __send_user_informations(firstname, email, password, creator):
    template = settings.NEW_ACCOUNT_TEMPLATE % (firstname,
                                                settings.SWORPDHISH_URL,
                                                email,
                                                password,
                                                settings.SWORPDHISH_URL)

    if creator.lower() == settings.USER_ACCOUNT_CREATION_MAIL_CONTACT:
        message = EmailMessage(from_email=settings.USER_ACCOUNT_CREATION_MAIL_SENDER,
                               subject=settings.USER_ACCOUNT_CREATION_MAIL_TITLE,
                               body=template,
                               to=[email],
                               cc=[settings.USER_ACCOUNT_CREATION_MAIL_CONTACT],
                               reply_to=[settings.USER_ACCOUNT_CREATION_MAIL_CONTACT])
    else:
        message = EmailMessage(from_email=settings.USER_ACCOUNT_CREATION_MAIL_SENDER,
                               subject=settings.USER_ACCOUNT_CREATION_MAIL_TITLE,
                               body=template,
                               to=[email],
                               cc=[settings.USER_ACCOUNT_CREATION_MAIL_CONTACT, creator],
                               reply_to=[settings.USER_ACCOUNT_CREATION_MAIL_CONTACT])
    message.send()


def __lost_password(firstname, email, password):
    template = settings.LOST_PASSWORD_TEMPLATE % (firstname,
                                                  settings.SWORPDHISH_URL,
                                                  email,
                                                  password)

    message = EmailMessage(from_email=settings.USER_ACCOUNT_CREATION_MAIL_SENDER,
                           subject=settings.USER_ACCOUNT_LOST_PASS_MAIL_TITLE,
                           body=template,
                           to=[email],
                           cc=[settings.USER_ACCOUNT_CREATION_MAIL_CONTACT],
                           reply_to=[settings.USER_ACCOUNT_CREATION_MAIL_CONTACT])
    message.send()


def user_login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(username=username, password=password)
        if user is not None:
            if request.POST.get('remember', None):
                request.session.set_expiry(0)
            else:
                request.session.set_expiry(600)
            if user.is_active:
                login(request, user)
                if request.user.swordphishuser.must_change_password:
                    return redirect('Authent:loginchangepwd')
                return redirect('Main:index')
            return render(request, 'LocalUsers/index.html', {'error': 'error'})
        else:
            return render(request, 'LocalUsers/index.html', {'error': 'error'})
    else:
        if request.user.is_authenticated:
            if request.user.swordphishuser.must_change_password:
                return redirect('Authent:loginchangepwd')
            return redirect('Main:index')
        return render(request, "LocalUsers/index.html")


def password_lost(request):
    if request.method == "GET":
        newform = LostpasswordForm()
        return render(request, 'LocalUsers/password_reset_form.html', {'lostpass': newform})

    if request.method == "POST":
        newform = LostpasswordForm(request.POST)
        if not newform.is_valid():
            return render(request, 'LocalUsers/password_reset_form.html', {'lostpass': newform})
        email = newform.cleaned_data["email"]
        tmp = SwordphishUser.objects.filter(user__email=email.lower())
        if len(tmp) == 1:
            user = tmp[0]
            password = User.objects.make_random_password()
            user.user.set_password(password)
            user.user.save()
            user.must_change_password = True
            user.save()
            __lost_password(user.user.first_name, email, password)

        return render(request, 'LocalUsers/password_reset_done.html')

    return HttpResponseForbidden()


def password_change_mandatory(request):
    if not request.user.is_authenticated():
        return redirect("Authent:login")
    if request.method == "GET":
        if not request.user.swordphishuser.must_change_password:
            return redirect("Main:index")
        changepwdform = ChangePasswordForm(instance=request.user)
        swordphishuser = SwordphishUserForm(instance=request.user.swordphishuser)
        return render(request, "LocalUsers/loginchangepassword.html",
                      {'changepassform': changepwdform, 'swordphishform': swordphishuser})

    if request.method == "POST":
        changepwdform = ChangePasswordForm(request.POST, instance=request.user)
        swordphishuser = SwordphishUserForm(request.POST, instance=request.user.swordphishuser)
        if not changepwdform.is_valid() or not swordphishuser.is_valid():
            return render(request, "LocalUsers/loginchangepassword.html",
                          {'changepassform': changepwdform, 'swordphishform': swordphishuser})

        editeduser = changepwdform.save(commit=False)
        editeduser.set_password(changepwdform.cleaned_data["password_confirmation"])
        editeduser.save()
        editedswordphishuser = swordphishuser.save(commit=False)
        editedswordphishuser.must_change_password = False
        editedswordphishuser.save()
        return redirect("Main:index")

    return HttpResponseForbidden()


@login_required
def myprofile(request):
    if request.method == "GET":
        userform = EditMyProfileForm(instance=request.user)
        swordphishuser = SwordphishUserForm(instance=request.user.swordphishuser)
        return render(request, "LocalUsers/editprofile.html",
                      {'userform': userform, 'swordphishform': swordphishuser})

    if request.method == "POST":
        userform = EditMyProfileForm(request.POST, instance=request.user)
        swordphishuser = SwordphishUserForm(request.POST, instance=request.user.swordphishuser)
        if userform.is_valid() and swordphishuser.is_valid():
            editeduser = userform.save(commit=False)

            if userform.cleaned_data["password_confirmation"] != "":
                editeduser.set_password(userform.cleaned_data["password_confirmation"])
                update_session_auth_hash(request, editeduser)

            editeduser.save()
            editedswordphishuser = swordphishuser.save(commit=False)
            editedswordphishuser.must_change_password = False
            editedswordphishuser.save()
            return HttpResponse("Ok")

        return render(request, "LocalUsers/editprofile.html",
                      {'userform': userform, 'swordphishform': swordphishuser})

    return HttpResponseForbidden()


def user_logout(request):
    logout(request)
    return redirect('Authent:login')


@login_required
def block_unblock_user(request, userid=None):
    user = get_object_or_404(SwordphishUser, id=userid)

    if not user.can_be_edited(request.user):
        return HttpResponseForbidden()

    if user.user.is_active:
        user.user.is_active = False
        user.user.save()
    else:
        user.user.is_active = True
        user.user.save()

    return HttpResponse("Ok")


@login_required
def edit_user(request, userid=None):
    user = get_object_or_404(SwordphishUser, id=userid)
    usermail = user.user.username

    if not user.can_be_edited(request.user):
        return HttpResponseForbidden()

    if request.method == "GET":
        userform = UserForm(instance=user.user)
        phishform = SwordphishUserForm(instance=user)
        return render(request, 'LocalUsers/edituser.html',
                      {
                            'swordphishform': phishform,
                            'userform': userform,
                            'userid': userid
                      })

    if request.method == "POST":
        userform = UserForm(request.POST, instance=user.user)
        swordphishform = SwordphishUserForm(request.POST, instance=user)

        if not userform.is_valid():
            return render(request, 'LocalUsers/edituser.html',
                          {
                              'swordphishform': swordphishform,
                              'userform': userform,
                              'userid': userid
                          })

        if not swordphishform.is_valid():
            return render(request, 'LocalUsers/edituser.html',
                          {
                                'swordphishform': swordphishform,
                                'userform': userform,
                                'userid': userid
                          })

        if userform.cleaned_data["email"] != usermail:
            if User.objects.filter(email=userform.cleaned_data["email"]).count() > 0:
                return render(request, 'LocalUsers/newuser.html',
                              {
                                    'swordphishform': swordphishform,
                                    'userform': userform,

LocalUsers/templates/LocalUsers/addentityadmin.html
{% load bootstrap3 %}
{% load i18n %}
<form class="modal-form" method="post" action="{% url 'Authent:add_entity_admin' entityid %}">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>{% trans 'Add Entity Admin' %}</h3>

      </div>
      <div class="modal-body">
        {% if admin_already_exists %}
          <div class="alert alert-danger alert-dismissible" id="error">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{% trans 'This user is already admin.' %}</strong><br/>
          </div>
        {% endif %}
        {% csrf_token %}
        {% bootstrap_form adminform %}
      </div>
      <div class="modal-footer">
           <input name="add" class="btn btn-primary" type="submit" value="Add" />
           <input name="cancel" class="btn" type="submit" value="Cancel" data-dismiss="modal"/>
      </div>
    </div>
  </div>
</form>

LocalUsers/templates/LocalUsers/adduserinregion.html
{% load bootstrap3 %}
{% load i18n %}
<form class="modal-form" method="post" action="{% url 'Authent:add_region_user' regionid %}">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>{% trans 'Add Region Member' %}</h3>

      </div>
      <div class="modal-body">
        {% if user_already_exists %}
          <div class="alert alert-danger alert-dismissible" id="error">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{% trans 'This user is already in this region.' %}</strong><br/>
          </div>
        {% endif %}
        {% csrf_token %}
        {% bootstrap_form userregionform %}
      </div>
      <div class="modal-footer">
           <input name="add" class="btn btn-primary" type="submit" value="Add" />
           <input name="cancel" class="btn" type="submit" value="Cancel" data-dismiss="modal"/>
      </div>
    </div>
  </div>
</form>

LocalUsers/templates/LocalUsers/editentity.html
{% load bootstrap3 %}
{% load i18n %}
<form class="modal-form" method="post" action="{% url 'Authent:edit_entity' entityid %}">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>{% trans 'Edit Entity' %}</h3>

      </div>
      <div class="modal-body">
        {% if entity_already_exists %}
          <div class="alert alert-danger alert-dismissible" id="error">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{% trans 'This entity already exists.' %}</strong><br/>
          </div>
        {% endif %}
        {% csrf_token %}
        {% bootstrap_form entityform %}
      </div>
      <div class="modal-footer">
           <input name="save" class="btn btn-primary" type="submit" value="Save" />
           <input name="cancel" class="btn" type="submit" value="Cancel" data-dismiss="modal"/>
      </div>
    </div>
  </div>
</form>

LocalUsers/templates/LocalUsers/edituser.html
{% load bootstrap3 %}
{% load i18n %}
<form class="modal-form" method="post" action="{% url 'Authent:edit_user' userid %}">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>{% trans 'Edit User' %}</h3>

      </div>
      <div class="modal-body">
        {% if user_already_exists %}
          <div class="alert alert-danger alert-dismissible" id="error">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{% trans 'This mail address already exists.' %}</strong><br/>
          </div>
        {% endif %}
        {% csrf_token %}
        {% bootstrap_form userform %}
        {% bootstrap_form swordphishform %}
      </div>
      <div class="modal-footer">
           <input name="save" class="btn btn-primary" type="submit" value="Save" />
           <input name="cancel" class="btn" type="submit" value="Cancel" data-dismiss="modal"/>
      </div>
    </div>
  </div>
</form>

LocalUsers/templates/LocalUsers/listentity.html
{% load bootstrap3 %}
{% load i18n %}
	<option value="">{% trans '--Select--' %}</option>
{% for entity in entitylist %}
	<option data-form="{%url 'Authent:list_entity_admins' entity.id %}" value="{{ entity.id }}">{{ entity.name }}</option>
{% endfor %}

LocalUsers/templates/LocalUsers/listentityadmins.html
{% load bootstrap3 %}
{% load i18n %}
<form class="form-inline">
	<div class="form-group">
		<label class="control-label" for="add_admin_button">{% trans "Modify Entity" %}</label>
		<button id="add_admin_button" type="submit" class="form-control btn btn-primary edit" data-toggle="modal" data-form="{% url 'Authent:edit_entity' entityid %}" data-target="#modal">Edit Entity</button>
		<button id="add_admin_button" type="submit" class="form-control btn btn-primary add" data-toggle="modal" data-form="{% url 'Authent:add_entity_admin' entityid %}" data-target="#modal">Add Admin</button>
	</div>
</form>
<h3 class="page-header">{% trans 'Existing Admins' %}</h3>
<div class="">
	<table class="table table-striped table-condensed">
		<thead>
			<tr>
				<th>{% trans "First name" %}</th>
	            <th>{% trans "Last name" %}</th>
	            <th>{% trans "Email" %}</th>
	            <th>{% trans "Phone" %}</th>
	            <th>&nbsp;</th>
	        </tr>
		</thead>
		<tbody>
			{% for user in userslist %}
			<tr>
				<td class="vert-align">{{ user.user.first_name }}</td>
				<td class="vert-align">{{ user.user.last_name }}</td>
				<td class="vert-align">{{ user.user.email }}</td>
				<td class="vert-align">{{ user.phone_number }}</td>
				<td class="vert-align">
					<button type="button" class="btn btn-default btn-xs edit" data-toggle="modal" data-form="{% url 'Authent:remove_entity_admin' entityid user.id %}" data-target="#modal">
					  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
					</button>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

LocalUsers/templates/LocalUsers/listregion.html
{% load bootstrap3 %}
{% load i18n %}
	<option value="">{% trans '--Select--' %}</option>
{% for region in regionlist %}
	<option data-form="{%url 'Authent:list_region_users' region.id %}" value="{{ region.id }}">{{ region.prettyname }}</option>
{% endfor %}

LocalUsers/templates/LocalUsers/listregionsusers.html
{% load bootstrap3 %}
{% load i18n %}
<form class="form-inline">
	<div class="form-group">
		<label class="control-label" for="add_admin_button">{% trans "Modify Region" %}</label>
			<button id="add_admin_button" type="submit" class="form-control btn btn-primary edit" data-toggle="modal" data-form="{% url 'Authent:edit_region' regionid %}" data-target="#modal">Edit Region</button>
			<button id="add_admin_button" type="submit" class="form-control btn btn-primary add" data-toggle="modal" data-form="{% url 'Authent:add_region_user' regionid %}" data-target="#modal">Add User</button>
	</div>
	</div>
</form>
<h3 class="page-header">{% trans 'Existing Users' %}</h3>
<div>
	<table class="table table-striped table-condensed">
		<thead>
			<tr>
				<th>{% trans "First name" %}</th>
	            <th>{% trans "Last name" %}</th>
	            <th>{% trans "Email" %}</th>
	            <th>{% trans "Phone" %}</th>
	            <th>&nbsp;</th>
	        </tr>
		</thead>
		<tbody>
			{% for user in userslist %}
			<tr>
				<td class="vert-align">{{ user.user.first_name }}</td>
				<td class="vert-align">{{ user.user.last_name }}</td>
				<td class="col-md-2 vert-align">{{ user.user.email }}</td>
				<td class="col-md-2 vert-align">{{ user.phone_number }}</td>
				<td class="col-md-1 vert-align">
					<button type="button" class="btn btn-default edit btn-xs" data-toggle="modal" data-form="{% url 'Authent:remove_region_user' regionid user.id %}" data-target="#modal">
					  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
					</button>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>

LocalUsers/templates/LocalUsers/listusers.html
{% load bootstrap3 %}
{% load i18n %}
<table class="table table-striped table-condensed">
	<thead>
		<tr>
			<th>{% trans "First name" %}</th>
            <th>{% trans "Last name" %}</th>
            <th>{% trans "Email" %}</th>
            <th>{% trans "Phone" %}</th>
            <th>{% trans "Status" %}</th>
            <th>&nbsp;</th>
        </tr>
	</thead>
	<tbody>
		{% for user in userslist %}
		<tr>
			<td class="vert-align">{{ user.0.user.first_name }}</td>
			<td class="vert-align">{{ user.0.user.last_name }}</td>
			<td class="col-md-2 vert-align">{{ user.0.user.email }}</td>
			<td class="col-md-2 vert-align">{{ user.0.phone_number }}</td>
			{% if user.0.user.is_active %}
			<td class="col-md-2 vert-align">{% trans 'Active' %}</td>
			{% else %}
			<td class="col-md-2 vert-align">{% trans 'Disabled' %}</td>
			{% endif %}
			<td class="col-md-1 vert-align">
			{% if user.1 %}
				<button type="button" class="btn btn-default btn-xs  edit" data-toggle="tooltip" data-placement="top" title="Edit User"  data-form="{% url 'Authent:edit_user' user.0.id %}" data-target="#modal">
				  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
				</button>
				{% if user.0.user != current_user %}
					{% if user.0.user.is_active %}
					<button type="button" class="btn btn-default btn-xs  silent" data-toggle="tooltip" data-placement="top" title="Block User"  data-form="{% url 'Authent:block_unblock_user' user.0.id %}" data-target="#modal">
					  <span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span>
					</button>
					{% else %}
					<button type="button" class="btn btn-default btn-xs  silent"  data-toggle="tooltip" data-placement="top" title="Unblock User"  data-form="{% url 'Authent:block_unblock_user' user.0.id %}" data-target="#modal">
					  <span class="glyphicon glyphicon-ok-circle" aria-hidden="true"></span>
					</button>
					{% endif %}
				{% endif %}
			{% endif %}
				<!--<button type="button" class="btn btn-default" aria-label="Edit">
				  <span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span>
				</button>-->
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>