Main/urls.py
from django.conf.urls import url
from Main import views

app_name = 'Main'

urlpatterns = [
    url(r'^$',
        views.index,
        name="index"),
    url(r'^$',
        views.campaign_overview,
        name="campaign_overview"),
    url(r'^targets$',
        views.campaign_targets,
        name="campaign_targets"),
    url(r'^campaigns/targets/createlist$',
        views.campaign_create_targets_list,
        name="campaign_create_targets_list"),
    url(r'^targets/deletelist/(?P<listid>\d+)$',
        views.campaign_delete_targets_list,
        name="campaign_delete_targets_list"),
    url(r'^targets/editlist/(?P<listid>\d+)$',
        views.campaign_edit_targets_list,
        name="campaign_edit_targets_list"),
    url(r'^targets/importtargerts/(?P<listid>\d+)$',
        views.campaign_import_targets_list,
        name="campaign_import_targets_list"),
    url(r'^targets/exporttargerts/(?P<listid>\d+)$',
        views.campaign_export_targets_list,
        name="campaign_export_targets_list"),
    url(r'^targets/createtarget/(?P<listid>\d+)$',
        views.campaign_create_target,
        name="campaign_create_target"),
    url(r'^targets/removetarget/(?P<listid>\d+)/(?P<targetid>\d+)$',
        views.campaign_delete_target,
        name="campaign_delete_target"),
    url(r'^targets/edittarget/(?P<listid>\d+)/(?P<targetid>\d+)$',
        views.campaign_edit_target,
        name="campaign_edit_target"),
    url(r'^targets/listtargets/(?P<listid>\d+)/(?P<page>\d+)?$',
        views.campaign_list_targets,
        name="campaign_list_targets"),
    url(r'^targets/lists/(?P<page>\d+)?$',
        views.campaign_list_targets_list,
        name="campaign_list_targets_list"),
    url(r'^templates$',
        views.campaign_templates,
        name="campaign_templates"),
    url(r'^templates/create/(?P<typeid>\d)(?:/(?P<duplicateid>\d+))?$',
        views.campaign_create_template,
        name="campaign_create_template"),
    url(r'^templates/edit/(?P<typeid>\d)/(?P<templateid>\d+)$',
        views.campaign_edit_template,
        name="campaign_edit_template"),
    url(r'^templates/delete/(?P<templateid>\d+)$',
        views.campaign_delete_template,
        name="campaign_delete_template"),
    url(r'^templates/view/(?P<templateid>\d+)$',
        views.campaign_view_template,
        name="campaign_view_template"),
    url(r'^templates/list/(?P<page>\d+)?$',
        views.campaign_list_template,
        name="campaign_list_template"),
    url(r'^campaigns$',
        views.campaign_campaigns,
        name="campaign_campaigns"),
    url(r'^campaigns/running$',
        views.campaign_running_campaigns,
        name="campaign_running_campaigns"),
    url(r'^campaigns/create/(?P<typeid>\d)(?:/(?P<duplicateid>\d+))?$',
        views.campaign_create_campaign,
        name="campaign_create_campaign"),
    url(r'^campaigns/edit/(?P<typeid>\d)/(?P<campaignid>\d+)$',
        views.campaign_edit_campaign,
        name="campaign_edit_campaign"),
    url(r'^campaigns/delete/(?P<campaignid>\d+)$',
        views.campaign_delete_campaign,
        name="campaign_delete_campaign"),
    url(r'^campaigns/test/(?P<campaignid>\d+)$',
        views.campaign_test_campaign,
        name="campaign_test_campaign"),
    url(r'^campaigns/download/(?P<campaignid>\d+)$',
        views.campaign_download_results,
        name="campaign_download_results"),
    url(r'^campaigns/dasbhoard/(?P<campaignid>\d+)$',
        views.campaign_display_dashboard,
        name="campaign_display_dashboard"),
    url(r'^campaigns/reportids/(?P<campaignid>\d+)$',
        views.campaign_submit_reported_ids,
        name="campaign_submit_reported_ids"),
    url(r'^campaigns/list/(?P<page>\d+)?$',
        views.campaign_list_campaigns,
        name="campaign_list_campaigns"),
    url(r'^campaigns/list-running/(?P<page>\d+)?$',
        views.campaign_list_running_campaigns,
        name="campaign_list_running_campaigns"),

    url(r'^admin/entities$',
        views.admin_entities,
        name="admin_entities"),
    url(r'^admin/regions$',
        views.admin_regions,
        name="admin_regions"),
    url(r'^admin/users$',
        views.admin_users,
        name="admin_users"),
    url(r'^result/click/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_target_click,
        name="campaign_target_click"),
    url(r'^result/displayawareness/(?P<campaignid>\d+)/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_display_awareness,
        name="campaign_display_awareness"),
    url(r'^result/getimage/(?P<templateid>\d+)/(?P<imgid>img\d+)$',
        views.internet_explorer_img_hack,
        name="getimage"),
    url(r'^result/img/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_target_openmail,
        name="campaign_target_openmail"),
    url(r'^result/report/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_target_reportmail,
        name="campaign_target_reportmail"),
    url(r'^result/attach/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_target_openattachment,
        name="campaign_target_openattachment"),
    url(r'^2985836c7501af76a0bdd92f1d120cd2/domains_feed',
        views.domains_feed,
        name="domains_feed"),
]

Swordphish/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('LocalUsers.urls')),
    url(r'^', include('Main.urls')),
]

Main/models.py
import datetime
import uuid
from base64 import b64decode
from smtplib import SMTPRecipientsRefused
from email.mime.image import MIMEImage
from email.header import Header
from bs4 import BeautifulSoup
from openpyxl import load_workbook, Workbook
from openpyxl.writer.excel import save_virtual_workbook
from openpyxl.styles import Font, Alignment
from ckeditor.fields import RichTextField
from django.db import models, transaction
from django.core.validators import validate_email
from django.core.exceptions import ObjectDoesNotExist
from django.forms import ValidationError
from django.core import mail
from django.conf import settings
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext as _
from django.core.validators import RegexValidator

from LocalUsers.models import SwordphishUser, get_admin
from Main.utils import send_alert_new_campaign


# Create your models here.
@python_2_unicode_compatible
class Attribute(models.Model):
    key = models.CharField(db_index=True, max_length=240)
    value = models.CharField(db_index=True, max_length=240)

    def __str__(self):
        return "%s => %s" % (self.key, self.value)

    class Meta:
        unique_together = ('key', 'value')


class Target(models.Model):
    mail_address = models.EmailField(db_index=True,)
    attributes = models.ManyToManyField(Attribute)

    def __str__(self):
        return self.mail_address

    def addAttribute(self, attribute, value):
        l = self.attributes.filter(key=attribute, value=value)
        if not l:
            newAtt = None
            try:
                newAtt = Attribute.objects.get(key=attribute, value=value)
            except ObjectDoesNotExist:
                newAtt = Attribute.objects.create(key=attribute, value=value)
            self.attributes.add(newAtt)
            self.save()

    def removeAttribute(self, attribute):
        self.attributes.remove(attribute)
        self.save()


@python_2_unicode_compatible
class TargetList(models.Model):
    class Meta:
        ordering = ["name", "-creation_date"]

    name = models.CharField(max_length=240)
    targets = models.ManyToManyField(Target)
    author = models.ForeignKey(SwordphishUser, null=True, on_delete=models.SET(get_admin))
    creation_date = models.DateTimeField(blank=True, default=datetime.datetime.now)

    def __str__(self):
        return self.name

    def loadTargetsFromUploadedXslx(self, uploadedFile):
        wb = load_workbook(filename=uploadedFile, read_only=True)
        ws = wb.active
        targets = {}
        header = next(ws.rows)
        tags_keys = [x.value for x in header[1:] if x.value is not None]
        for row in ws.iter_rows(row_offset=1):
            if row[0] and row[0].value:
                email = row[0].value.lower()
                tags_values = [x.value if x.value is not None else "N/A" for x in row[1:]]
                tags = dict(zip(tags_keys, tags_values))
                try:
                    validate_email(email)
                except ValidationError:
                    raise ValidationError(email)
                targets[email] = tags
        new_targets = []
        with transaction.atomic():
            for email in targets:
                if not self.targets.filter(mail_address=email).exists():
                    tmp = Target.objects.create(mail_address=email)
                    atts = []
                    for tag, value in targets[email].items():
                        try:
                            newatt = Attribute.objects.get(key=tag, value=value)
                        except ObjectDoesNotExist:
                            newatt = Attribute.objects.create(key=tag, value=value)
                        atts.append(newatt)
                    tmp.attributes.add(*atts)
                    new_targets.append(tmp)
            self.targets.add(*new_targets)

        transaction.commit()

        return True

    def removeTarget(self, target):
        self.targets.remove(target)
        self.targets.filter(mail_address=target.mail_address).delete()

    def addTarget(self, email, attributes):
        newTarget = Target(mail_address=email)
        newTarget.save()
        for att, value in attributes.iteritems():
            newTarget.addAttribute(att, value)

    def is_used(self):
        return len(Campaign.objects.filter(targets=self.id)) > 0

    def export_to_xlsx(self):
        targets = self.targets.all()
        wb = Workbook()
        ws = wb.active
        tags = set()
        mails = {}
        for target in targets:
            mails[target.mail_address] = {}
            attributes = target.attributes.all()
            for attribute in attributes:
                mails[target.mail_address][attribute.key] = attribute.value
                tags.add(attribute.key)
        header = list(tags)
        header.insert(0, "email")
        ws.append(header)
        for address in mails:
            line = []
            line.append(address)
            for tag in tags:
                if tag in mails[address]:
                    line.append(mails[address][tag])
                else:
                    line.append("N/A")
            ws.append(line)

        c = ws['B2']
        ws.freeze_panes = c
        head = ws[1]
        ft = Font(bold=True)
        al = Alignment(horizontal="center", vertical="center")
        for cell in head:
            cell.font = ft
        for row in ws.rows:
            for cell in row:
                cell.alignment = al
        return save_virtual_workbook(wb)


@python_2_unicode_compatible
class AnonymousTarget(models.Model):
    uniqueid = models.CharField(db_index=True, max_length=36, default=uuid.uuid4)
    attributes = models.ManyToManyField(Attribute)
    mail_sent_time = models.DateTimeField(blank=True, null=True)
    mail_opened = models.BooleanField(default=False)
    mail_opened_time = models.DateTimeField(blank=True, null=True)
    link_clicked = models.BooleanField(default=False)
    link_clicked_time = models.DateTimeField(blank=True, null=True)
    attachment_opened = models.BooleanField(default=False)
    attachment_opened_time = models.DateTimeField(blank=True, null=True)
    form_submitted = models.BooleanField(default=False)
    form_submitted_time = models.DateTimeField(blank=True, null=True)
    reported = models.BooleanField(default=False)
    reported_time = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.uniqueid

    def addAttribute(self, attribute, value):
        l = self.attributes.filter(key=attribute, value=value)
        self.attributes.add(l[0])

    def importAttributes(self, target):
        l = target.attributes.all()
        for att in l:
            self.attributes.add(att)


@python_2_unicode_compatible
class PhishmailDomain(models.Model):
    class Meta:
        ordering = ["domain"]

    domain = models.CharField(max_length=50)

    def __str__(self):
        return self.domain


@python_2_unicode_compatible
class Template(models.Model):

    class Meta:
        ordering = ["name", "-creation_date"]

    TEMPLATE_TYPE = [
        ('#1', _('Mail with link')),
        ('1', _('Mail with link template')),
        ('#2', _('Mail with attachment')),
        ('2', _('Mail with attachment template')),
        ('3', _('Attachment template')),
        ('#3', _('Action after click')),
        ('4', _('Redirection')),
        ('5', _('Awareness template')),
        ('6', _('Fake form template')),
        ('7', _('Fake ransomware template')),
    ]

    template_type = models.CharField(max_length=1, choices=TEMPLATE_TYPE, default=1)
    name = models.CharField(max_length=200)
    author = models.ForeignKey(SwordphishUser, on_delete=models.SET(get_admin))
    creation_date = models.DateTimeField(auto_now_add=True, blank=True)
    public = models.BooleanField(default=False)
    title = models.CharField(max_length=100)
    timeout = models.PositiveIntegerField(default=10)
    text = RichTextField()

    def __str__(self):
        return self.name

    def is_used(self):
        if self.template_type == "1" or self.template_type == "2":
            return bool(Campaign.objects.filter(mail_template=self.id))
        if self.template_type == "3":
            return bool(Campaign.objects.filter(attachment_template=self.id))
        if self.template_type == "4" or self.template_type == "5":
            return bool(Campaign.objects.filter(onclick_action=self.id))
        if self.template_type == "6":
            return bool(Campaign.objects.filter(fake_form=self.id))
        if self.template_type == "7":
            return bool(Campaign.objects.filter(fake_ransom=self.id))

        return False


@python_2_unicode_compatible
class Campaign(models.Model):

    class Meta:
        ordering = ["-start_date", "-end_date", "creation_date"]

    CAMPAIGN_TYPES = [
        ("1", _("Simple")),
        ("2", _("With Attachment")),
        ("3", _("Fake Form")),
        ("4", _("Fake Ransomware"))
    ]

    CAMPAIGN_STATUS = [
        ('1', _("Not Started")),
        ('2', _("Running")),
        ('3', _("Finished")),
    ]

    campaign_type = models.CharField(max_length=1, choices=CAMPAIGN_TYPES, default="1")

    name = models.CharField(max_length=200)

    author = models.ForeignKey(SwordphishUser, on_delete=models.SET(get_admin))

    creation_date = models.DateTimeField(auto_now_add=True, blank=True)

    start_date = models.DateTimeField()

    end_date = models.DateTimeField()

    targets = models.ManyToManyField(TargetList)

    targets_count = models.IntegerField(default=0)

    anonymous_targets = models.ManyToManyField(AnonymousTarget)

    status = models.CharField(max_length=1, choices=CAMPAIGN_STATUS, default="1")

    mail_template = models.ForeignKey(Template,
                                      related_name='%(class)s_mail',
                                      on_delete=models.PROTECT)

Main/templates/Main/Campaigns/Campaigns/campaigns.html
{% extends 'Main/topmenus.html' %}

{% load bootstrap3 %}
{% load i18n %}


{% block swordphish_content %}


<div class="modal fade" id="modal" tabindex="-1" data-keyboard="false" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

<div class="starter-template">
    <h3 class="page-header">{% trans 'Create Campaigns' %}</h3>
    <form class="form-inline">
		<div class="form-group">
	    		<label class="control-label" for="createentity">{% trans 'Create Campaign' %}</label>
		    	<select class="form-control" name="template_format" id="button-url">
		    	{% for entry in types %}
				    <option value="{% url 'Main:campaign_create_campaign' entry.0 %}">{{ entry.1 }}</option>
				{% endfor %}
		    	</select>
		</div>
	    	<button id="createtemplate" type="button" class="btn btn-primary new-selected form-control" data-toggle="modal" data-target="#modal">{% trans 'Create' %}</button>
	</form>
</div>

<div class="starter-template">
    <h3 class="page-header">{% trans 'Existing Campaigns' %}</h3>
	<div class="dynamic" id="users" data-form="{%url 'Main:campaign_list_campaigns' %}"></div>
</div>

{% endblock %}

Main/templates/Main/Campaigns/Campaigns/createcampaign.html
{% load bootstrap3 %}
{% load i18n %}
<form class="modal-form" enctype="multipart/form-data" method="post" action="{% url 'Main:campaign_create_campaign' typeid %}">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>{% trans 'Create new campaign' %}</h3>
      </div>
      <div class="modal-body">
        {% csrf_token %}
        <link href="{{STATIC_URL}}/bootstrap3_datetime/css/bootstrap-datetimepicker.min.css" type="text/css" media="all" rel="stylesheet">
        <script type="text/javascript" src="{{STATIC_URL}}/bootstrap3_datetime/js/moment.min.js"></script>
        <script type="text/javascript" src="{{STATIC_URL}}/bootstrap3_datetime/js/bootstrap-datetimepicker.min.js"></script>
        {% if campaign_already_exists %}
          <div class="alert alert-danger alert-dismissible" id="error">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{% trans 'Campaign already exists.' %}</strong><br/>
          </div>
        {% endif %}
        {{ campaignform.media }}
        {% bootstrap_form campaignform %}
      </div>
      <div class="modal-footer">
           <input name="create" class="btn btn-primary" type="submit" value="Create" />
           <input name="cancel" class="btn" type="submit" value="Cancel" data-dismiss="modal"/>
      </div>
    </div>
  </div>
</form>

Main/templates/Main/Campaigns/Campaigns/deletecampaign.html
{% load bootstrap3 %}
{% load i18n %}
<form class="modal-form" method="post" action="{% url 'Main:campaign_delete_campaign' campaign.id %}">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>{% trans 'Delete Campaign' %}</h3>

      </div>
      <div class="modal-body">
        {% csrf_token %}
        <label class="control-label" for="name">{% trans "Campaign name" %}</label>
        <input id="targtlistname" type="text" name="name" class="form-control" value="{{ campaign.name }}" readonly>
        <label class="control-label" for="stdate">{% trans "Start date" %}</label>
        <input id="targtlistname" type="text" name="stdate" class="form-control" value="{{ campaign.start_date }}" readonly>
        <label class="control-label" for="endate">{% trans "End date" %}</label>
        <input id="targtlistname" type="text" name="endate" class="form-control" value="{{ campaign.end_date }}" readonly>
        <div class="modal-footer">
          <input name="remove" class="btn btn-primary" type="submit" value="Confirm" />
          <input name="cancel" class="btn" type="submit" value="Cancel" data-dismiss="modal"/>
      </div>
    </div>
  </div>
</form>

Main/templates/Main/Campaigns/Campaigns/list_running_campaigns.html
{% load bootstrap3 %}
{% load i18n %}
<table class="table table-striped table-condensed">
	<thead>
		<tr>
      <th>{% trans "Contact" %}</th>
			<th>{% trans "Sender" %}</th>
			<th>{% trans "Host domain" %}</th>
      <th>{% trans "Start date" %}</th>
      <th>{% trans "End date" %}</th>
      <th>{% trans "Type" %}</th>
      <th>&nbsp;</th>
    </tr>
	</thead>
	<tbody>
		{% for campaign in campaignlist.object_list %}
		<tr>
			<td class="vert-align">{{ campaign.author.user.email }}</td>
			<td class="vert-align">{{ campaign.from_name }}@{{ campaign.from_domain }}</td>
      {% if campaign.campaign_type == "1" or campaign.campaign_type == "3" %}
        {% if campaign.host_subdomain != None %}
          <td class="vert-align">{{ campaign.host_domain }}</td>
        {% else %}
          <td class="vert-align">{{ campaign.host_subdomain }}.{{ campaign.host_domain }}</td>
        {% endif %}
      {% else %}
      <td class="vert-align">Irrelevant...</td>
      {% endif %}
			<td class="vert-align">{{ campaign.start_date|date:"d/m/Y H:i"}}</td>
			<td class="vert-align">{{ campaign.end_date|date:"d/m/Y H:i"}}</td>
			<td class="vert-align">{{ campaign.get_campaign_type_display }}</td>
			<td class="vert-align">
        <button type="button" class="btn btn-default popup btn-xs" data-toggle="tooltip" data-placement="top" title="Display Mail Template" data-form="{% url 'Main:campaign_view_template' campaign.mail_template.id %}">
            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
        </button>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
<nav>
  <ul class="pagination">
  	{% if campaignlist.has_previous %}
    <li>
      <a class="paging" data-form="{% url 'Main:campaign_list_running_campaigns' campaignlist.previous_page_number %}" href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% else %}
	<li class="disabled">
      <a href="#" disabled aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
   	{% endif %}
   	{% for page in campaignlist.pages %}
      {% if page %}
     		{% if campaignlist.number == page %}
      		<li class="active"><a href="#">{{ page }}</a></li>
     		{% else %}
     			<li><a data-form="{% url 'Main:campaign_list_running_campaigns' page %}" class="paging" href="#">{{ page }}</a></li>
     		{% endif %}
      {% else %}
        <li class="disabled"><span aria-hidden="true">...</span></li>
      {% endif %}
    {% endfor %}
    {% if campaignlist.has_next %}
    <li>
      <a class="paging" data-form="{% url 'Main:campaign_list_running_campaigns' campaignlist.next_page_number %}" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% else %}
    <li class="disabled">
      <a href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>

Main/templates/Main/Campaigns/Campaigns/listcampaigns.html
{% load bootstrap3 %}
{% load i18n %}
<table class="table table-striped table-condensed">
	<thead>
		<tr>
      <th>{% trans "Start date" %}</th>
      <th>{% trans "End date" %}</th>
			<th>{% trans "Campaign name" %}</th>
			<th>{% trans "Author" %}</th>
      <th>{% trans "Creation date" %}</th>
      <th>{% trans "Type" %}</th>
      <th>{% trans "Status" %}</th>
      <th>&nbsp;</th>
    </tr>
	</thead>
	<tbody>
		{% for campaign in campaignlist.object_list %}
		<tr>
      <td class="vert-align">{{ campaign.start_date|date:"d/m/Y H:i"}}</td>
      <td class="vert-align">{{ campaign.end_date|date:"d/m/Y H:i"}}</td>
  		<td class="vert-align">{{ campaign.name }}</td>
			<td class="vert-align">{{ campaign.author.user.email }}</td>
	    <td class="vert-align">{{ campaign.creation_date|date:"d/m/Y"}}</td>
  		<td class="vert-align">{{ campaign.get_campaign_type_display }}</td>
			<td class="vert-align">{{ campaign.get_status_display }}</td>
			<td class="vert-align">
			<button type="button" class="btn btn-default btn-xs edit" data-toggle="tooltip" data-placement="top" title="Test Campaign"  data-form="{% url 'Main:campaign_test_campaign' campaign.id %}" data-target="#modal">
			  <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
			</button>
      <button type="button" class="btn btn-default edit btn-xs" data-toggle="tooltip" data-placement="top" title="Duplicate Campaign"  data-form="{% url 'Main:campaign_create_campaign' campaign.campaign_type campaign.id %}">
            <span class="glyphicon glyphicon-copy" aria-hidden="true"></span>
        </button>
			{% if campaign.status == "1" and campaign.author in current_user.visible_users %}
				<button type="button" class="btn btn-default btn-xs edit" data-toggle="tooltip" data-placement="top" title="Edit Campaign" data-form="{% url 'Main:campaign_edit_campaign' campaign.campaign_type campaign.id %}" data-target="#modal">
				  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
				</button>
			{% endif %}
			{% if campaign.status != "2" and campaign.author in current_user.visible_users %}
				<button type="button" class="btn btn-default btn-xs edit" data-toggle="tooltip" data-placement="top" title="Delete Campaign"  data-form="{% url 'Main:campaign_delete_campaign' campaign.id %}" data-target="#modal">
					  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
				</button>
			{% endif %}
			{% if campaign.status in "23"  and campaign.author in current_user.visible_users %}
        <button type="button" class="btn btn-default btn-xs edit" data-toggle="tooltip" data-placement="top" title="Display Dashboard"  data-form="{% url 'Main:campaign_display_dashboard' campaign.id %}" data-target="#modal">
            <span class="glyphicon glyphicon-dashboard" aria-hidden="true"></span>
        </button>
        <button type="button" class="btn btn-default btn-xs edit" data-toggle="tooltip" data-placement="top" title="Submit Report IDs"  data-form="{% url 'Main:campaign_submit_reported_ids' campaign.id %}" data-target="#modal">
            <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
        </button>
      {% endif %}
      {% if campaign.status == "3" and campaign.author in current_user.visible_users %}
				<button type="button" class="btn btn-default btn-xs download" data-toggle="tooltip" data-placement="top" title="Download Results"  data-form="{% url 'Main:campaign_download_results' campaign.id %}" data-target="#modal">
					  <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span>
				</button>
			{% endif %}
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
<nav>
  <ul class="pagination">
  	{% if campaignlist.has_previous %}
    <li>
      <a class="paging" data-form="{% url 'Main:campaign_list_campaigns' campaignlist.previous_page_number %}" href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% else %}
	<li class="disabled">
      <a href="#" disabled aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
   	{% endif %}
   	{% for page in campaignlist.pages %}
      {% if page %}
     		{% if campaignlist.number == page %}
      		<li class="active"><a href="#">{{ page }}</a></li>
     		{% else %}
     			<li><a data-form="{% url 'Main:campaign_list_campaigns' page %}" class="paging" href="#">{{ page }}</a></li>
     		{% endif %}
      {% else %}
        <li class="disabled"><span aria-hidden="true">...</span></li>
      {% endif %}
    {% endfor %}
    {% if campaignlist.has_next %}
    <li>
      <a class="paging" data-form="{% url 'Main:campaign_list_campaigns' campaignlist.next_page_number %}" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% else %}
    <li class="disabled">
      <a href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>