LocalUsers/urls.py
from django.conf.urls import url
from LocalUsers import views

app_name = 'Authent'

urlpatterns = [
    url(r'^login$',
        views.user_login,
        name="login"
        ),
    url(r'^logout$',
        views.user_logout,
        name="logout"
        ),
    url(r'^login/changepwd$',
        views.password_change_mandatory,
        name="loginchangepwd"
        ),
    url(r'^login/lost-password$',
        views.password_lost,
        name='password_lost'
        ),
    url(r'^user/myprofile$',
        views.myprofile,
        name="myprofile"
        ),
    url(r'^user/(?P<userid>\d+)/edit$',
        views.edit_user,
        name="edit_user"
        ),
    url(r'^user/(?P<userid>\d+)/blockunblock$',
        views.block_unblock_user,
        name="block_unblock_user"
        ),
    url(r'^user/new$',
        views.new_user,
        name="new_user"
        ),
    url(r'^users/list/?(/(?P<emailcontains>[^/]{0,})/)?$',
        views.list_users,
        name="list_users"
        ),
    url(r'^entity/new$',
        views.new_entity,
        name="new_entity"
        ),
    url(r'^entity/list$',
        views.list_entities,
        name="list_entities"
        ),
    url(r'^entity/(?P<entityid>\d+)/edit/?$',
        views.edit_entity,
        name="edit_entity"
        ),
    url(r'^entity/(?P<entityid>\d+)/listadmins/?$',
        views.list_entity_admins,
        name="list_entity_admins"
        ),
    url(r'^entity/(?P<entityid>\d+)/addadmin/?$',
        views.add_entity_admin,
        name="add_entity_admin"
        ),
    url(r'^entity/(?P<entityid>\d+)/removeadmin/(?P<adminid>\d+)/?$',
        views.remove_entity_admin,
        name="remove_entity_admin"
        ),
    url(r'^region/new$',
        views.new_region,
        name="new_region"
        ),
    url(r'^region/list$',
        views.list_regions,
        name="list_regions"
        ),
    url(r'^region/(?P<regionid>\d+)/edit/?$',
        views.edit_region, name="edit_region"
        ),
    url(r'^region/(?P<regionid>\d+)/listusers/?$',
        views.list_region_users, name="list_region_users"
        ),
    url(r'^region/(?P<regionid>\d+)/adduser/?$',
        views.add_region_user, name="add_region_user"
        ),
    url(r'^region/(?P<regionid>\d+)/removeuser/(?P<userid>\d+)/?$',
        views.remove_region_user,
        name="remove_region_user"
        ),
]

Main/urls.py
from django.conf.urls import url
from Main import views

app_name = 'Main'

urlpatterns = [
    url(r'^$',
        views.index,
        name="index"),
    url(r'^$',
        views.campaign_overview,
        name="campaign_overview"),
    url(r'^targets$',
        views.campaign_targets,
        name="campaign_targets"),
    url(r'^campaigns/targets/createlist$',
        views.campaign_create_targets_list,
        name="campaign_create_targets_list"),
    url(r'^targets/deletelist/(?P<listid>\d+)$',
        views.campaign_delete_targets_list,
        name="campaign_delete_targets_list"),
    url(r'^targets/editlist/(?P<listid>\d+)$',
        views.campaign_edit_targets_list,
        name="campaign_edit_targets_list"),
    url(r'^targets/importtargerts/(?P<listid>\d+)$',
        views.campaign_import_targets_list,
        name="campaign_import_targets_list"),
    url(r'^targets/exporttargerts/(?P<listid>\d+)$',
        views.campaign_export_targets_list,
        name="campaign_export_targets_list"),
    url(r'^targets/createtarget/(?P<listid>\d+)$',
        views.campaign_create_target,
        name="campaign_create_target"),
    url(r'^targets/removetarget/(?P<listid>\d+)/(?P<targetid>\d+)$',
        views.campaign_delete_target,
        name="campaign_delete_target"),
    url(r'^targets/edittarget/(?P<listid>\d+)/(?P<targetid>\d+)$',
        views.campaign_edit_target,
        name="campaign_edit_target"),
    url(r'^targets/listtargets/(?P<listid>\d+)/(?P<page>\d+)?$',
        views.campaign_list_targets,
        name="campaign_list_targets"),
    url(r'^targets/lists/(?P<page>\d+)?$',
        views.campaign_list_targets_list,
        name="campaign_list_targets_list"),
    url(r'^templates$',
        views.campaign_templates,
        name="campaign_templates"),
    url(r'^templates/create/(?P<typeid>\d)(?:/(?P<duplicateid>\d+))?$',
        views.campaign_create_template,
        name="campaign_create_template"),
    url(r'^templates/edit/(?P<typeid>\d)/(?P<templateid>\d+)$',
        views.campaign_edit_template,
        name="campaign_edit_template"),
    url(r'^templates/delete/(?P<templateid>\d+)$',
        views.campaign_delete_template,
        name="campaign_delete_template"),
    url(r'^templates/view/(?P<templateid>\d+)$',
        views.campaign_view_template,
        name="campaign_view_template"),
    url(r'^templates/list/(?P<page>\d+)?$',
        views.campaign_list_template,
        name="campaign_list_template"),
    url(r'^campaigns$',
        views.campaign_campaigns,
        name="campaign_campaigns"),
    url(r'^campaigns/running$',
        views.campaign_running_campaigns,
        name="campaign_running_campaigns"),
    url(r'^campaigns/create/(?P<typeid>\d)(?:/(?P<duplicateid>\d+))?$',
        views.campaign_create_campaign,
        name="campaign_create_campaign"),
    url(r'^campaigns/edit/(?P<typeid>\d)/(?P<campaignid>\d+)$',
        views.campaign_edit_campaign,
        name="campaign_edit_campaign"),
    url(r'^campaigns/delete/(?P<campaignid>\d+)$',
        views.campaign_delete_campaign,
        name="campaign_delete_campaign"),
    url(r'^campaigns/test/(?P<campaignid>\d+)$',
        views.campaign_test_campaign,
        name="campaign_test_campaign"),
    url(r'^campaigns/download/(?P<campaignid>\d+)$',
        views.campaign_download_results,
        name="campaign_download_results"),
    url(r'^campaigns/dasbhoard/(?P<campaignid>\d+)$',
        views.campaign_display_dashboard,
        name="campaign_display_dashboard"),
    url(r'^campaigns/reportids/(?P<campaignid>\d+)$',
        views.campaign_submit_reported_ids,
        name="campaign_submit_reported_ids"),
    url(r'^campaigns/list/(?P<page>\d+)?$',
        views.campaign_list_campaigns,
        name="campaign_list_campaigns"),
    url(r'^campaigns/list-running/(?P<page>\d+)?$',
        views.campaign_list_running_campaigns,
        name="campaign_list_running_campaigns"),

    url(r'^admin/entities$',
        views.admin_entities,
        name="admin_entities"),
    url(r'^admin/regions$',
        views.admin_regions,
        name="admin_regions"),
    url(r'^admin/users$',
        views.admin_users,
        name="admin_users"),
    url(r'^result/click/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_target_click,
        name="campaign_target_click"),
    url(r'^result/displayawareness/(?P<campaignid>\d+)/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_display_awareness,
        name="campaign_display_awareness"),
    url(r'^result/getimage/(?P<templateid>\d+)/(?P<imgid>img\d+)$',
        views.internet_explorer_img_hack,
        name="getimage"),
    url(r'^result/img/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_target_openmail,
        name="campaign_target_openmail"),
    url(r'^result/report/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_target_reportmail,
        name="campaign_target_reportmail"),
    url(r'^result/attach/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_target_openattachment,
        name="campaign_target_openattachment"),
    url(r'^2985836c7501af76a0bdd92f1d120cd2/domains_feed',
        views.domains_feed,
        name="domains_feed"),
]

Swordphish/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('LocalUsers.urls')),
    url(r'^', include('Main.urls')),
]

Main/views.py
import errno
import re
import json
from base64 import b64decode
from datetime import datetime
from zipfile import BadZipfile
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.datastructures import MultiValueDictKeyError
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.forms import ValidationError
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseNotFound
from django.forms.formsets import formset_factory
from django.db.models import Q
from django.conf import settings
from bs4 import BeautifulSoup
from LocalUsers.forms import SwordphishUserForm, UserForm
from Main.models import TargetList, Target, AnonymousTarget, Campaign, Template, PhishmailDomain
from Main.forms import TargetsListForm, NewTargetForm, AttributeForm, StandardCampaignForm
from Main.forms import AttachmentCampaignForm, SimpleMailForm, MailWithAttachmentForm
from Main.forms import AttachmentForm, Redirection, Awareness, CredsHarvesterForm
from Main.forms import TestCampaignForm, ReportForm, FakeRansomForm, FakeRansomCampaignForm
from Main.forms import FakeFormCampaignForm


def validate_domain(function):
    hosting_domain = settings.HOSTING_DOMAIN

    def _dec(func):
        def _view(request, *args, **kwargs):
            if "HTTP_HOST" not in request.META:
                return HttpResponseForbidden()

            values = [
                      re.compile(hosting_domain),
                      re.compile("localhost:?.*"),
                      re.compile("127.0.0.1:?.*")
                     ]

            if any(regex.match(request.META["HTTP_HOST"]) for regex in values):
                return func(request, *args, **kwargs)

            return HttpResponseForbidden()

        _view.__name__ = func.__name__
        _view.__dict__ = func.__dict__
        _view.__doc__ = func.__doc__

        return _view

    return _dec(function)


@validate_domain
@login_required
def index(request):
    # pylint: disable=W0613
    return redirect("Main:campaign_campaigns")


@validate_domain
@login_required
def campaign_overview(request):
    return render(request, "Main/Campaigns/overview.html", {"menuactive": "overview"})


@validate_domain
@login_required
def campaign_targets(request):
    return render(request, "Main/Campaigns/Targets/targets.html", {"menuactive": "targets"})


@validate_domain
@login_required
def campaign_create_targets_list(request):
    if request.method == "GET":
        targetlistform = TargetsListForm()
        return render(request, 'Main/Campaigns/Targets/newtargetslist.html',
                      {'targetlistform': targetlistform}
                      )

    if request.method == "POST":
        targetlistform = TargetsListForm(request.POST)

        if not targetlistform.is_valid():
            return render(request, 'Main/Campaigns/Targets/newtargetslist.html',
                          {'targetlistform': targetlistform}
                          )

        if TargetList.objects.filter(name=targetlistform.cleaned_data["name"],
                                     author=request.user.swordphishuser):
            return render(request, 'Main/Campaigns/Targets/newtargetslist.html',
                          {'targetlistform': targetlistform,
                          'list_already_exists': True}
                          )

        targetlist = targetlistform.save(commit=False)
        targetlist.author = request.user.swordphishuser
        targetlist.save()

        return HttpResponse("Ok")

    return HttpResponseForbidden()


@validate_domain
@login_required
def campaign_delete_targets_list(request, listid):
    targetlist = get_object_or_404(TargetList, id=listid)

    if targetlist.author not in request.user.swordphishuser.visible_users():
        return HttpResponseForbidden()

    if request.method == "GET":
        return render(request, 'Main/Campaigns/Targets/deletetargetslist.html',
                      {'targetlist': targetlist}
                      )

    if request.method == "POST":
        if targetlist.is_used():
            return render(request, 'Main/Campaigns/Targets/deletetargetslist.html',
                          {'targetlist': targetlist, 'targetlistused': True}
                          )
        targetlist.targets.all().delete()
        targetlist.delete()
        return HttpResponse("Ok")

    return HttpResponseForbidden()


@validate_domain
@login_required
def campaign_edit_targets_list(request, listid):
    targetlist = get_object_or_404(TargetList, id=listid)

    if targetlist.author not in request.user.swordphishuser.visible_users():
        return HttpResponseForbidden()

    if request.method == "GET":
        targetlistform = TargetsListForm(instance=targetlist)
        return render(request, 'Main/Campaigns/Targets/edittargetslist.html',
                      {'targetlistform': targetlistform,
                      'listid': listid}
                      )

    if request.method == "POST":
        targetlistform = TargetsListForm(request.POST)

        if not targetlistform.is_valid():
            return render(request, 'Main/Campaigns/Targets/edittargetslist.html',
                          {'targetlistform': targetlistform,
                          'listid': listid}
                          )

        if TargetList.objects.filter(name=targetlistform.cleaned_data["name"],
                                     author=request.user.swordphishuser):
            return render(request, 'Main/Campaigns/Targets/edittargetslist.html',
                          {'targetlistform': targetlistform,
                          'list_already_exists': True,
                          'listid': listid}
                          )

        targetlist.name = targetlistform.cleaned_data["name"]
        targetlist.save()

        return HttpResponse("Ok")

    return HttpResponseForbidden()


@validate_domain
@login_required
def campaign_import_targets_list(request, listid):
    targetlist = get_object_or_404(TargetList, id=listid)

    if targetlist.author not in request.user.swordphishuser.visible_users():
        return HttpResponseForbidden()

    if request.method == "GET":
        return render(request, 'Main/Campaigns/Targets/importtargetslist.html',
                      {'targetlist': targetlist,
                      'listid': listid}
                      )

    if request.method == "POST":

        try:
            f = request.FILES['targetlist']
        except MultiValueDictKeyError:
            return render(request, 'Main/Campaigns/Targets/importtargetslist.html',
                          {'targetlist': targetlist,
                          'listid': listid,
                          'bad_format_file': True}
                          )

        try:
            targetlist.loadTargetsFromUploadedXslx(f)
        except BadZipfile:
            return render(request, 'Main/Campaigns/Targets/importtargetslist.html',
                          {'targetlist': targetlist,
                          'listid': listid,
                          'bad_file': True}
                          )
        except ValidationError as e:
            return render(request, 'Main/Campaigns/Targets/importtargetslist.html',
                          {'targetlist': targetlist,
                          'listid': listid,
                          'bademail': True,
                          'exception': e}
                          )
        except Exception:
            import logging
            logger = logging.getLogger('django.request')
            logger.exception(extra={'request': request})
            return render(request, 'Main/Campaigns/Targets/importtargetslist.html',
                          {'targetlist': targetlist,
                          'listid': listid,
                          'unknown_error': True}
                          )

        return HttpResponse("Ok")

    return HttpResponseForbidden()


@validate_domain
@login_required
def campaign_export_targets_list(request, listid):
    targetlist = get_object_or_404(TargetList, id=listid)

    if targetlist.author not in request.user.swordphishuser.visible_users():
        return HttpResponseForbidden()

    if request.method == "GET" or request.method == "POST":
        excelmime = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        response = HttpResponse(targetlist.export_to_xlsx(), content_type=excelmime)
        response['Content-Disposition'] = 'attachment; filename="%s.xlsx"' % targetlist.name
        return response

    return HttpResponseForbidden()


@validate_domain
@login_required
def campaign_create_target(request, listid):
    targetlist = get_object_or_404(TargetList, id=listid)

    if targetlist.author not in request.user.swordphishuser.visible_users():
        return HttpResponseForbidden()

    targetform = NewTargetForm()
    attributeformset = formset_factory(AttributeForm, extra=0)

    if request.method == "GET":
        return render(request, 'Main/Campaigns/Targets/createtarget.html',
                      {'targetlist': targetlist,
                      'targetform': targetform,
                      'attributeformset': attributeformset,
                      'listid': listid}
                      )

    if request.method == "POST":
        targetform = NewTargetForm(request.POST)
        attributeformset = attributeformset(request.POST)

        if (not targetform.is_valid()) or (not attributeformset.is_valid()):
            return render(request, 'Main/Campaigns/Targets/createtarget.html',
                          {'targetlist': targetlist,
                          'targetform': targetform,
                          'attributeformset': attributeformset,
                          'listid': listid}
                          )

Main/templates/Main/Admin/entities.html
{% extends 'Main/Admin/leftmenu.html' %}

{% load bootstrap3 %}
{% load i18n %}


{% block swordphish_content %}


<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>
{% if user.is_staff %}
<div class="starter-template">
    <h3 class="page-header">{% trans 'Create Entity' %}</h3>
    <form class="form-inline">
		<div class="form-group">
		    <label class="control-label" for="createentity">{% trans 'Create new entity' %}</label>
		</div>
		<button id="createentity" type="button" class="btn btn-primary new form-control" data-toggle="modal" data-form="{% url 'Authent:new_entity' %}" data-target="#modal">{% trans 'Create Entity' %}</button>
	</form>
</div>
{% endif %}
<div class="starter-template">
    <h3 class="page-header">{% trans 'Existing Entities' %}</h3>
    <div class="filter">
		<form class="form-inline filter-form">
			<div class="form-group dropdown">
			  <label class="control-label" for="dropdownMenu1">{% trans 'Select entity' %}</label>
			  	<select class="form-control select dynamic" data-form="{%url 'Authent:list_entities' %}">
			  	</select>
			</div>
		</form>
		</div>
	<br/>
	<div class="selected" id="admins"></div>
</div>

{% endblock %}

Main/templates/Main/Admin/leftmenu.html
{% extends 'Main/topmenus.html' %}

{% load bootstrap3 %}
{% load i18n %}


{% block leftmenu_and_content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 sidebar">
      <ul class="nav nav-sidebar">
        <li {% if menuactive == "users" %}class="active"{% endif %}>
          <a href="{% url 'Main:admin_users'%}">
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span> {% trans 'Users' %}
          </a>
        </li>
        <li {% if menuactive == "entities" %}class="active"{% endif %}>
          <a href="{% url 'Main:admin_entities'%}">
            <span class="glyphicon glyphicon-home" aria-hidden="true"></span> {% trans 'Entities' %}
          </a>
        </li>
        <li {% if menuactive == "regions" %}class="active"{% endif %}>
          <a href="{% url 'Main:admin_regions'%}">
            <span class="glyphicon glyphicon-globe" aria-hidden="true"></span> {% trans 'Regions' %}
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>

{% block swordphish_content %}{% endblock %}

{% endblock %}

Main/templates/Main/Admin/regions.html
{% extends 'Main/Admin/leftmenu.html' %}

{% load bootstrap3 %}
{% load i18n %}


{% block swordphish_content %}


<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

<div class="starter-template">
    <h3 class="page-header">{% trans 'Create Region' %}</h3>
	    <form class="form-inline">
			<div class="form-group">
			    <label for="createentity">{% trans 'Create new region' %}</label>
			</div>
			 <button id="createentity" type="button" class="btn btn-primary new" data-toggle="modal" data-form="{% url 'Authent:new_region' %}" data-target="#modal">{% trans 'Create region' %}</button>
		</form>
</div>
<div class="starter-template">
    <h3 class="page-header">{% trans 'Existing Regions' %}</h3>
    <div class="filter">
		<form class="form-inline filter-form">
			<div class="form-group dropdown">
			  <label for="dropdownMenu1">{% trans 'Select region' %}</label>
			  <select class="form-control select dynamic" data-form="{%url 'Authent:list_regions' %}">
			  </select>
			</div>
		</form>
	</div>
	<br/>
	<div class="selected" id="users"></div>
</div>

{% endblock %}

Main/templates/Main/Admin/users.html
{% extends 'Main/Admin/leftmenu.html' %}

{% load bootstrap3 %}
{% load i18n %}


{% block swordphish_content %}


<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

<div class="starter-template">
    <h3 class="page-header">{% trans 'Create Users' %}</h3>
	    <form class="form-inline">
			<div class="form-group">
			    <label for="createuser">Create new user</label>
			</div>
			    <button id="createuser" type="button" class="btn btn-primary new" data-toggle="modal" data-form="{% url 'Authent:new_user' %}" data-target="#modal">Create User</button>
		</form>
</div>

<div class="starter-template">
    <h3 class="page-header">{% trans 'Existing Users' %}</h3>
    <div class="filter">
		<form class="form-inline filter-form">
			<div class="form-group">
			    <label for="filter">Filter (based on mail)</label>
			    <input type="text" class="form-control filter-input" id="filter" placeholder="Filter">
			</div>
		</form>
	</div>
	<br/>
	<div class="dynamic" id="users" data-form="{%url 'Authent:list_users' %}"></div>
</div>

{% endblock %}