Main/urls.py
from django.conf.urls import url
from Main import views

app_name = 'Main'

urlpatterns = [
    url(r'^$',
        views.index,
        name="index"),
    url(r'^$',
        views.campaign_overview,
        name="campaign_overview"),
    url(r'^targets$',
        views.campaign_targets,
        name="campaign_targets"),
    url(r'^campaigns/targets/createlist$',
        views.campaign_create_targets_list,
        name="campaign_create_targets_list"),
    url(r'^targets/deletelist/(?P<listid>\d+)$',
        views.campaign_delete_targets_list,
        name="campaign_delete_targets_list"),
    url(r'^targets/editlist/(?P<listid>\d+)$',
        views.campaign_edit_targets_list,
        name="campaign_edit_targets_list"),
    url(r'^targets/importtargerts/(?P<listid>\d+)$',
        views.campaign_import_targets_list,
        name="campaign_import_targets_list"),
    url(r'^targets/exporttargerts/(?P<listid>\d+)$',
        views.campaign_export_targets_list,
        name="campaign_export_targets_list"),
    url(r'^targets/createtarget/(?P<listid>\d+)$',
        views.campaign_create_target,
        name="campaign_create_target"),
    url(r'^targets/removetarget/(?P<listid>\d+)/(?P<targetid>\d+)$',
        views.campaign_delete_target,
        name="campaign_delete_target"),
    url(r'^targets/edittarget/(?P<listid>\d+)/(?P<targetid>\d+)$',
        views.campaign_edit_target,
        name="campaign_edit_target"),
    url(r'^targets/listtargets/(?P<listid>\d+)/(?P<page>\d+)?$',
        views.campaign_list_targets,
        name="campaign_list_targets"),
    url(r'^targets/lists/(?P<page>\d+)?$',
        views.campaign_list_targets_list,
        name="campaign_list_targets_list"),
    url(r'^templates$',
        views.campaign_templates,
        name="campaign_templates"),
    url(r'^templates/create/(?P<typeid>\d)(?:/(?P<duplicateid>\d+))?$',
        views.campaign_create_template,
        name="campaign_create_template"),
    url(r'^templates/edit/(?P<typeid>\d)/(?P<templateid>\d+)$',
        views.campaign_edit_template,
        name="campaign_edit_template"),
    url(r'^templates/delete/(?P<templateid>\d+)$',
        views.campaign_delete_template,
        name="campaign_delete_template"),
    url(r'^templates/view/(?P<templateid>\d+)$',
        views.campaign_view_template,
        name="campaign_view_template"),
    url(r'^templates/list/(?P<page>\d+)?$',
        views.campaign_list_template,
        name="campaign_list_template"),
    url(r'^campaigns$',
        views.campaign_campaigns,
        name="campaign_campaigns"),
    url(r'^campaigns/running$',
        views.campaign_running_campaigns,
        name="campaign_running_campaigns"),
    url(r'^campaigns/create/(?P<typeid>\d)(?:/(?P<duplicateid>\d+))?$',
        views.campaign_create_campaign,
        name="campaign_create_campaign"),
    url(r'^campaigns/edit/(?P<typeid>\d)/(?P<campaignid>\d+)$',
        views.campaign_edit_campaign,
        name="campaign_edit_campaign"),
    url(r'^campaigns/delete/(?P<campaignid>\d+)$',
        views.campaign_delete_campaign,
        name="campaign_delete_campaign"),
    url(r'^campaigns/test/(?P<campaignid>\d+)$',
        views.campaign_test_campaign,
        name="campaign_test_campaign"),
    url(r'^campaigns/download/(?P<campaignid>\d+)$',
        views.campaign_download_results,
        name="campaign_download_results"),
    url(r'^campaigns/dasbhoard/(?P<campaignid>\d+)$',
        views.campaign_display_dashboard,
        name="campaign_display_dashboard"),
    url(r'^campaigns/reportids/(?P<campaignid>\d+)$',
        views.campaign_submit_reported_ids,
        name="campaign_submit_reported_ids"),
    url(r'^campaigns/list/(?P<page>\d+)?$',
        views.campaign_list_campaigns,
        name="campaign_list_campaigns"),
    url(r'^campaigns/list-running/(?P<page>\d+)?$',
        views.campaign_list_running_campaigns,
        name="campaign_list_running_campaigns"),

    url(r'^admin/entities$',
        views.admin_entities,
        name="admin_entities"),
    url(r'^admin/regions$',
        views.admin_regions,
        name="admin_regions"),
    url(r'^admin/users$',
        views.admin_users,
        name="admin_users"),
    url(r'^result/click/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_target_click,
        name="campaign_target_click"),
    url(r'^result/displayawareness/(?P<campaignid>\d+)/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_display_awareness,
        name="campaign_display_awareness"),
    url(r'^result/getimage/(?P<templateid>\d+)/(?P<imgid>img\d+)$',
        views.internet_explorer_img_hack,
        name="getimage"),
    url(r'^result/img/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_target_openmail,
        name="campaign_target_openmail"),
    url(r'^result/report/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_target_reportmail,
        name="campaign_target_reportmail"),
    url(r'^result/attach/(?P<targetid>[a-z\d]{8}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{4}-[a-z\d]{12})$',
        views.campaign_target_openattachment,
        name="campaign_target_openattachment"),
    url(r'^2985836c7501af76a0bdd92f1d120cd2/domains_feed',
        views.domains_feed,
        name="domains_feed"),
]

Swordphish/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('LocalUsers.urls')),
    url(r'^', include('Main.urls')),
]

Main/views.py
import errno
import re
import json
from base64 import b64decode
from datetime import datetime
from zipfile import BadZipfile
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.datastructures import MultiValueDictKeyError
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.forms import ValidationError
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseNotFound
from django.forms.formsets import formset_factory
from django.db.models import Q
from django.conf import settings
from bs4 import BeautifulSoup
from LocalUsers.forms import SwordphishUserForm, UserForm
from Main.models import TargetList, Target, AnonymousTarget, Campaign, Template, PhishmailDomain
from Main.forms import TargetsListForm, NewTargetForm, AttributeForm, StandardCampaignForm
from Main.forms import AttachmentCampaignForm, SimpleMailForm, MailWithAttachmentForm
from Main.forms import AttachmentForm, Redirection, Awareness, CredsHarvesterForm
from Main.forms import TestCampaignForm, ReportForm, FakeRansomForm, FakeRansomCampaignForm
from Main.forms import FakeFormCampaignForm


def validate_domain(function):
    hosting_domain = settings.HOSTING_DOMAIN

    def _dec(func):
        def _view(request, *args, **kwargs):
            if "HTTP_HOST" not in request.META:
                return HttpResponseForbidden()

            values = [
                      re.compile(hosting_domain),
                      re.compile("localhost:?.*"),
                      re.compile("127.0.0.1:?.*")
                     ]

            if any(regex.match(request.META["HTTP_HOST"]) for regex in values):
                return func(request, *args, **kwargs)

            return HttpResponseForbidden()

        _view.__name__ = func.__name__
        _view.__dict__ = func.__dict__
        _view.__doc__ = func.__doc__

        return _view

    return _dec(function)


@validate_domain
@login_required
def index(request):
    # pylint: disable=W0613
    return redirect("Main:campaign_campaigns")


@validate_domain
@login_required
def campaign_overview(request):
    return render(request, "Main/Campaigns/overview.html", {"menuactive": "overview"})


@validate_domain
@login_required
def campaign_targets(request):
    return render(request, "Main/Campaigns/Targets/targets.html", {"menuactive": "targets"})


@validate_domain
@login_required
def campaign_create_targets_list(request):
    if request.method == "GET":
        targetlistform = TargetsListForm()
        return render(request, 'Main/Campaigns/Targets/newtargetslist.html',
                      {'targetlistform': targetlistform}
                      )

    if request.method == "POST":
        targetlistform = TargetsListForm(request.POST)

        if not targetlistform.is_valid():
            return render(request, 'Main/Campaigns/Targets/newtargetslist.html',
                          {'targetlistform': targetlistform}
                          )

        if TargetList.objects.filter(name=targetlistform.cleaned_data["name"],
                                     author=request.user.swordphishuser):
            return render(request, 'Main/Campaigns/Targets/newtargetslist.html',
                          {'targetlistform': targetlistform,
                          'list_already_exists': True}
                          )

        targetlist = targetlistform.save(commit=False)
        targetlist.author = request.user.swordphishuser
        targetlist.save()

        return HttpResponse("Ok")

    return HttpResponseForbidden()


@validate_domain
@login_required
def campaign_delete_targets_list(request, listid):
    targetlist = get_object_or_404(TargetList, id=listid)

    if targetlist.author not in request.user.swordphishuser.visible_users():
        return HttpResponseForbidden()

    if request.method == "GET":
        return render(request, 'Main/Campaigns/Targets/deletetargetslist.html',
                      {'targetlist': targetlist}
                      )

    if request.method == "POST":
        if targetlist.is_used():
            return render(request, 'Main/Campaigns/Targets/deletetargetslist.html',
                          {'targetlist': targetlist, 'targetlistused': True}
                          )
        targetlist.targets.all().delete()
        targetlist.delete()
        return HttpResponse("Ok")

    return HttpResponseForbidden()


@validate_domain
@login_required
def campaign_edit_targets_list(request, listid):
    targetlist = get_object_or_404(TargetList, id=listid)

    if targetlist.author not in request.user.swordphishuser.visible_users():
        return HttpResponseForbidden()

    if request.method == "GET":
        targetlistform = TargetsListForm(instance=targetlist)
        return render(request, 'Main/Campaigns/Targets/edittargetslist.html',
                      {'targetlistform': targetlistform,
                      'listid': listid}
                      )

    if request.method == "POST":
        targetlistform = TargetsListForm(request.POST)

        if not targetlistform.is_valid():
            return render(request, 'Main/Campaigns/Targets/edittargetslist.html',
                          {'targetlistform': targetlistform,
                          'listid': listid}
                          )

        if TargetList.objects.filter(name=targetlistform.cleaned_data["name"],
                                     author=request.user.swordphishuser):
            return render(request, 'Main/Campaigns/Targets/edittargetslist.html',
                          {'targetlistform': targetlistform,
                          'list_already_exists': True,
                          'listid': listid}
                          )

        targetlist.name = targetlistform.cleaned_data["name"]
        targetlist.save()

        return HttpResponse("Ok")

    return HttpResponseForbidden()


@validate_domain
@login_required
def campaign_import_targets_list(request, listid):
    targetlist = get_object_or_404(TargetList, id=listid)

    if targetlist.author not in request.user.swordphishuser.visible_users():
        return HttpResponseForbidden()

    if request.method == "GET":
        return render(request, 'Main/Campaigns/Targets/importtargetslist.html',
                      {'targetlist': targetlist,
                      'listid': listid}
                      )

    if request.method == "POST":

        try:
            f = request.FILES['targetlist']
        except MultiValueDictKeyError:
            return render(request, 'Main/Campaigns/Targets/importtargetslist.html',
                          {'targetlist': targetlist,
                          'listid': listid,
                          'bad_format_file': True}
                          )

        try:
            targetlist.loadTargetsFromUploadedXslx(f)
        except BadZipfile:
            return render(request, 'Main/Campaigns/Targets/importtargetslist.html',
                          {'targetlist': targetlist,
                          'listid': listid,
                          'bad_file': True}
                          )
        except ValidationError as e:
            return render(request, 'Main/Campaigns/Targets/importtargetslist.html',
                          {'targetlist': targetlist,
                          'listid': listid,
                          'bademail': True,
                          'exception': e}
                          )
        except Exception:
            import logging
            logger = logging.getLogger('django.request')
            logger.exception(extra={'request': request})
            return render(request, 'Main/Campaigns/Targets/importtargetslist.html',
                          {'targetlist': targetlist,
                          'listid': listid,
                          'unknown_error': True}
                          )

        return HttpResponse("Ok")

    return HttpResponseForbidden()


@validate_domain
@login_required
def campaign_export_targets_list(request, listid):
    targetlist = get_object_or_404(TargetList, id=listid)

    if targetlist.author not in request.user.swordphishuser.visible_users():
        return HttpResponseForbidden()

    if request.method == "GET" or request.method == "POST":
        excelmime = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        response = HttpResponse(targetlist.export_to_xlsx(), content_type=excelmime)
        response['Content-Disposition'] = 'attachment; filename="%s.xlsx"' % targetlist.name
        return response

    return HttpResponseForbidden()


@validate_domain
@login_required
def campaign_create_target(request, listid):
    targetlist = get_object_or_404(TargetList, id=listid)

    if targetlist.author not in request.user.swordphishuser.visible_users():
        return HttpResponseForbidden()

    targetform = NewTargetForm()
    attributeformset = formset_factory(AttributeForm, extra=0)

    if request.method == "GET":
        return render(request, 'Main/Campaigns/Targets/createtarget.html',
                      {'targetlist': targetlist,
                      'targetform': targetform,
                      'attributeformset': attributeformset,
                      'listid': listid}
                      )

    if request.method == "POST":
        targetform = NewTargetForm(request.POST)
        attributeformset = attributeformset(request.POST)

        if (not targetform.is_valid()) or (not attributeformset.is_valid()):
            return render(request, 'Main/Campaigns/Targets/createtarget.html',
                          {'targetlist': targetlist,
                          'targetform': targetform,
                          'attributeformset': attributeformset,
                          'listid': listid}
                          )

Main/templates/Main/Campaigns/Targets/createtarget.html
{% load bootstrap3 %}
{% load i18n %}
<form class="modal-form" enctype="multipart/form-data" method="post" action="{% url 'Main:campaign_create_target' listid %}">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>{% trans 'Create new target' %}</h3>
      </div>
      <div class="modal-body">
        {% if target_already_exists %}
          <div class="alert alert-danger alert-dismissible" id="error">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{% trans 'Target already exists.' %}</strong><br/>
          </div>
        {% endif %}
        {% csrf_token %}
        <div class="form-group">
        <label class="control-label" for="targtlistname">{% trans "Target list" %}</label>
        <input id="targtlistname" type="text" name="targtlistname" class="form-control" value="{{ targetlist.name }}" readonly>
        </div>
        {% bootstrap_form targetform %}
        <div class="form-group">
        <button class="btn btn-success btn-sm" id="bt_add_sorte" type="button">Add attribute</button>
        </div>
        {{ attributeformset.management_form }}
        <div id="formsetZone">
          {% for form in attributeformset %}
            <div class="nsorte">
              {% bootstrap_form form %}
            </div>
          {% endfor %}
        </div>
      </div>
      <div class="modal-footer">
           <input name="create" class="btn btn-primary" type="submit" value="Create" />
           <input name="cancel" class="btn" type="submit" value="Cancel" data-dismiss="modal"/>
      </div>
    </div>
  </div>
</form>

<!-- Element à copier pour un ajout au formset -->
<div style="display:none;">
    <div id="eform" class="nsorte" >
        {% bootstrap_form attributeformset.empty_form%}
        <div class='btn btn-warning btn-sm bt_rm_sorte'>
                <i class='glyphicon glyphicon-trash'></i>
        </div>
    </div>
</div>

Main/templates/Main/Campaigns/Targets/deletetarget.html
{% load bootstrap3 %}
{% load i18n %}
<form class="modal-form" method="post" action="{% url 'Main:campaign_delete_target' targetlist.id target.id %}">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>{% trans 'Delete Target' %}</h3>

      </div>
      <div class="modal-body">
        {% if notinlist %}
          <div class="alert alert-danger alert-dismissible" id="error">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{% trans 'This target is not present in this list.' %}</strong><br/>
          </div>
        {% endif %}
        {% csrf_token %}
        <label class="control-label" for="targtlistname">{% trans "Target list" %}</label>
        <input id="targtlistname" type="text" name="targtlistname" class="form-control" value="{{ targetlist.name }}" readonly>
        <label class="control-label" for="target">{% trans "Target" %}</label>
        <input type="text" id="author" name="target" class="form-control" value="{{ target.mail_address }}" readonly>
        <div class="modal-footer">
          <input name="remove" class="btn btn-primary" type="submit" value="Confirm" />
          <input name="cancel" class="btn" type="submit" value="Cancel" data-dismiss="modal"/>
      </div>
    </div>
  </div>
</form>

Main/templates/Main/Campaigns/Targets/listtargets.html
{% load bootstrap3 %}
{% load i18n %}
<form class="modal-form" enctype="multipart/form-data" method="post" action="{% url 'Main:campaign_create_target' listid %}">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">×</button>
        <h3>{% trans 'List targets' %}</h3>
      </div>
      <div class="modal-body">
        {% if target_already_exists %}
          <div class="alert alert-danger alert-dismissible" id="error">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <strong>{% trans 'Target already exists.' %}</strong><br/>
          </div>
        {% endif %}
        {% csrf_token %}
        <div class="form-group">
        <label class="control-label" for="targtlistname">{% trans "Target list" %}</label>
        <input id="targtlistname" type="text" name="targtlistname" class="form-control" value="{{ listname }}" readonly>
        </div>
        <div class="form-group">
        <table class="table table-striped table-condensed">
          <thead>
            <tr>
                <th>{% trans "Email" %}</th>
                <th>&nbsp;</th>
            </tr>
          </thead>
          <tbody>
            {% for target in targets.object_list %}
            <tr>
              <td class="vert-align">{{ target.mail_address }}</td>
              {% if editable %}
              <td class="col-md-3 vert-align">
                <button type="button" class="btn btn-xs btn-default edit" data-toggle="modal" data-form="{% url 'Main:campaign_edit_target' targetlist.id target.id %}" data-target="#modal" data-toggle="tooltip" data-placement="top" title="Edit Target">
                  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
                </button>
                <button type="button" class="btn btn-xs btn-default edit" data-toggle="modal" data-form="{% url 'Main:campaign_delete_target' targetlist.id target.id %}" data-target="#modal" data-toggle="tooltip" data-placement="top" title="Delete Target">
                    <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                </button>
              {% endif %}
                <!--<button type="button" class="btn btn-default" aria-label="Edit">
                  <span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span>
                </button>-->
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <nav>
          <ul class="pagination">
            {% if targets.has_previous %}
            <li>
              <a class="paging" data-form="{% url 'Main:campaign_list_targets' targetlist.id targets.previous_page_number %}" href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            {% else %}
          <li class="disabled">
              <a href="#" disabled aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            {% endif %}
            {% for page in targets.pages %}
              {% if page %}
                {% ifequal targets.number page %}
                  <li class="active"><a href="#">{{ page }}</a></li>
                {% else %}
                  <li><a data-form="{% url 'Main:campaign_list_targets' targetlist.id page %}" class="paging" href="#">{{ page }}</a></li>
                {% endifequal %}
              {% else %}
                <li class="disabled"><span aria-hidden="true">...</span></li>
              {% endif %}
            {% endfor %}
            {% if targets.has_next %}
              <li>
                <a class="paging" data-form="{% url 'Main:campaign_list_targets' targetlist.id targets.next_page_number %}" href="#" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
              {% else %}
              <li class="disabled">
                <a href="#" aria-label="Next">
                  <span aria-hidden="true">&raquo;</span>
                </a>
              </li>
            {% endif %}
          </ul>
        </nav>
        </div>
      </div>
      <div class="modal-footer">
           <input name="cancel" class="btn" type="submit" value="Close" data-dismiss="modal"/>
      </div>
    </div>
  </div>
</form>

Main/templates/Main/Campaigns/Targets/listtargetslists.html
{% load bootstrap3 %}
{% load i18n %}
<table class="table table-striped table-condensed">
	<thead>
		<tr>
            <th>{% trans "Creation date" %}</th>
			<th>{% trans "List name" %}</th>
            <th>{% trans "Author" %}</th>
            <th>{% trans "Size" %}</th>
            <th>&nbsp;</th>
        </tr>
	</thead>
	<tbody>
		{% for targetlist in targetslists.object_list %}
		<tr>
			<td class="vert-align">{{ targetlist.creation_date|date:"d/m/Y H:i"}}</td>
			<td class="vert-align">{{ targetlist.name }}</td>
			<td class="vert-align">{{ targetlist.author.user.email }}</td>
			<td class="vert-align">{{ targetlist.targets.count }}</td>
			<td class="vert-align">
				<button type="button" class="btn btn-default btn-xs edit" data-toggle="tooltip" data-placement="top" title="List Targets" data-form="{% url 'Main:campaign_list_targets' targetlist.id %}" data-target="#modal">
					  <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
				</button>
				{% if targetlist.author in current_user.visible_users %}
				<button type="button" class="btn btn-default btn-xs edit" data-toggle="tooltip" data-placement="top" title="Edit Targets List"  data-form="{% url 'Main:campaign_edit_targets_list' targetlist.id %}" data-target="#modal">
				  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
				</button>
				<button type="button" class="btn btn-default btn-xs edit" data-toggle="tooltip" data-placement="top" title="Import Targets with XLSX" data-form="{% url 'Main:campaign_import_targets_list' targetlist.id %}" data-target="#modal">
					  <span class="glyphicon glyphicon-import" aria-hidden="true"></span>
				</button>
				<button type="button" class="btn btn-default btn-xs download" data-toggle="tooltip" data-placement="top" title="Export Targets as XLSX"  data-form="{% url 'Main:campaign_export_targets_list' targetlist.id %}">
					  <span class="glyphicon glyphicon-export" aria-hidden="true"></span>
				</button>
				<button type="button" class="btn btn-default btn-xs edit" data-toggle="tooltip" data-placement="top" title="Create Target Manually" data-form="{% url 'Main:campaign_create_target' targetlist.id %}" data-target="#modal">
					  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
				</button>
				<button type="button" class="btn btn-default btn-xs edit" data-toggle="tooltip" data-placement="top" title="Delete Targets List" data-form="{% url 'Main:campaign_delete_targets_list' targetlist.id %}" data-target="#modal">
					  <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
				</button>
				{% endif %}
				<!--<button type="button" class="btn btn-default btn-sm" aria-label="Edit">
				  <span class="glyphicon glyphicon-ban-circle" aria-hidden="true"></span>
				</button>-->
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
<nav>
  <ul class="pagination">
  	{% if targetslists.has_previous %}
    <li>
      <a class="paging" data-form="{% url 'Main:campaign_list_targets_list' targetslists.previous_page_number %}" href="#" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% else %}
	<li class="disabled">
      <a href="#" disabled aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
   	{% endif %}
   	{% for page in targetslists.pages %}
   		{% if page %}
	   		{% ifequal targetslists.number page %}
	    		<li class="active"><a href="#">{{ page }}</a></li>
	   		{% else %}
	   			<li><a data-form="{% url 'Main:campaign_list_targets_list' page %}" class="paging" href="#">{{ page }}</a></li>
	   		{% endifequal %}
	   	{% else %}
        <li class="disabled"><span aria-hidden="true">...</span></li>
      {% endif %}
    {% endfor %}
    {% if targetslists.has_next %}
    <li>
      <a class="paging" data-form="{% url 'Main:campaign_list_targets_list' targetslists.next_page_number %}" href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% else %}
    <li class="disabled">
      <a href="#" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>

Main/templates/Main/Campaigns/Targets/targets.html
{% extends 'Main/Campaigns/leftmenu.html' %}

{% load bootstrap3 %}
{% load i18n %}


{% block swordphish_content %}


<div class="modal fade" id="modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

<div class="starter-template">
    <h3 class="page-header">{% trans 'Create Targets List' %}</h3>
    <form class="form-inline">
		<div class="form-group">
		    <label class="control-label" for="createentity">{% trans 'Create new list' %}</label>
		    <button id="createentity" type="button" class="btn btn-primary new form-control" data-toggle="modal" data-form="{% url 'Main:campaign_create_targets_list' %}" data-target="#modal">{% trans 'Create List' %}</button>
		</div>
	</form>
</div>

<div class="starter-template">
    <h3 class="page-header">{% trans 'Existing Targets Lists' %}</h3>
	<div class="dynamic" id="users" data-form="{%url 'Main:campaign_list_targets_list' %}"></div>
</div>

{% endblock %}